---
- name: Delete RDS instance
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars/common-vars.yml
  tasks:
    - name: load json variables
      set_fact:
        db_info: "{{ lookup('file', '../data.json') | from_json }}"

    - name: set base facts
      set_fact:
        target_account: "{{ db_info['targets'][environment_name]['account_id'] }}"
        target_id: "{{ db_info['targets'][environment_name]['id'] }}"
        delete_db_instance: "{{ lookup('env', 'DELETE_DB_INSTANCE') or 'no'}}"

    - name: target database instance id
      debug:
        msg: "{{ target_id }}"

    - name: set iam role facts
      set_fact:
        target_iam_role: "{{ 'arn:aws:iam::' + target_account + ':role/terraform' }}"

    - name: get aws credentials
      include: ../../creds/playbook.yml

    - name: delete alfresco snapshot
      rds_snapshot:
        db_snapshot_identifier: "{{ snapshot_name }}-final"
        state: absent
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        security_token: "{{ aws_security_token }}"
        wait: yes
      when: delete_db_instance | bool

    - name: remove the target instance with a final snapshot
      rds_instance:
        id: "{{ target_id }}"
        state: absent
        final_snapshot_identifier: "{{ snapshot_name }}-final"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        security_token: "{{ aws_security_token }}"
      when: delete_db_instance | bool
