---
- name: Create Param Store entry
  hosts: localhost
  connection: local
  vars_files:
    - ../../vars/common-vars.yml
  tasks:
    - name: set iam role facts
      set_fact:
        target_iam_role: "{{ lookup('env', 'TERRAGRUNT_IAM_ROLE') }}"
        snapshot_prefix: "{{ lookup('env', 'EBS_SNAPSHOT_NAME') or 'solr_refresh_snapshot' }}"

    - name: get aws credentials
      include: ../../creds/playbook.yml

    - name: Create snapshot param entry
      aws_ssm_parameter_store:
        name: "/alfresco/solr/ebs/snapshot_ids/{{ item }}"
        description: "Used for Solr EBS volume refresh"
        string_type: "String"
        value: "{{ new_id }}"
        overwrite_value: "always"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        security_token: "{{ aws_security_token }}"
        region: "{{ aws_region }}"
      loop:
        - eu-west-2a
        - eu-west-2b
        - eu-west-2c

    - name: manage eu-west-2a snapshot id
      include_tasks: ./update_ssm.yml
      vars:
        - az_name: eu-west-2a

    - name: manage eu-west-2b snapshot id
      include_tasks: ./update_ssm.yml
      vars:
        - az_name: eu-west-2b

    - name: manage eu-west-2c snapshot id
      include_tasks: ./update_ssm.yml
      vars:
        - az_name: eu-west-2c
