version: "3"

services:
  builder:
    build:
      context: ./build
      dockerfile: Dockerfile
    image: lambda_builder:local
    volumes:
      - ${PWD}/src/build:/opt/data/build
    entrypoint: [ "sh", "/opt/data/build/build.sh" ]
