---
version: 0.2

phases:
  pre_build:
    commands:
      - source configs/common.properties
      - make get_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make ${ACTION_TYPE} component=common
      - make ${ACTION_TYPE} component=s3buckets
      - make ${ACTION_TYPE} component=certs
      - make ${ACTION_TYPE} component=iam
      - make ${ACTION_TYPE} component=security-groups
