---
version: 0.2

env:
  variables:
    GIT_BRANCH: "master"

phases:
  pre_build:
    commands:
      - make get_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make build component=ami_permissions
      - make build component=solr
      - make build component=asg
      - make build component=waf
