---
version: 0.2

env:
  variables:
    GITHUB_ORG: ministryofjustice
    TARGET_BRANCH: develop
  parameter-store:
    GITHUB_USER: "/dev/jenkins/hmpps/integration/user/name"
    GITHUB_TOKEN: "/manually/created/engineering/dev/codepipeline/github/accesstoken"
    GITHUB_EMAIL: "/jenkins/github/email"
  git-credential-helper: yes

phases:
  pre_build:
    commands:
      - make get_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make build component=ami_permissions
      - make build component=solr
      - make build component=asg
      - make build component=waf
      - ansible-playbook utils/github/playbook.yml

