---
version: 0.2

env:
  variables:
    GIT_BRANCH: "feature/add-custom-work-dir-to-alf-dev"

phases:
  pre_build:
    commands:
      - make get_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make build component=database
