---
version: 0.2

phases:
  pre_build:
    commands:
      - make get_configs
  build:
    commands:
      - export HMPPS_BUILD_WORK_DIR=${CODEBUILD_SRC_DIR}
      - make build component=efs
      - make build component=elasticache-memcached
      - make build component=elk-migration
