version: "3.7"

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-apps}
    ports:
      - "6379:6379"

  worker:
    image: mojdigitalstudio/redis-s3-sync:latest
    volumes:
      - ${HOME}/.aws:/root/.aws
    environment:
      - AWS_PROFILE=hmpps-token
      - AWS_ROLE_ARN=${TERRAGRUNT_IAM_ROLE}
      - REDISTOGO_URL=redis://:apps@redis:6379
