version: "3.7"

services:
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass ${REDIS_PASSWORD:-apps}
    ports:
      - "6379:6379"

  worker:
    build:
      context: s3sync
      dockerfile: Dockerfile
    image: mojdigitalstudio/redis-s3-sync:latest
    volumes:
      - ${HOME}/.aws:/root/.aws
      - ./s3sync:/usr/src/app
    environment:
      - AWS_PROFILE=hmpps-token
      - AWS_ROLE_ARN=arn:aws:iam::563502482979:role/terraform
      - REDISTOGO_URL=redis://:apps@redis:6379
      - SOURCE_BUCKET=tf-alfresco-dev-alfresco-storage-s3bucket
      - DESTINATION_BUCKET=dn-src-bucket
