
version: "3"

services:
  elasticsearch-manager:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:0.0.205-alpha
    environment:
      - APP_ENVIRONMENT=dev
      - ES_HOST=elasticsearch
      - ES_S3_BUCKET=${ES_S3_BUCKET}
    volumes:
      - /opt/scripts:/opt/scripts
      - /opt/local:/opt/local
    entrypoint: [ "sh", "/opt/scripts/es5-restore.sh" ]
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - ES_VERSION=5.6.16
    volumes:
      - /opt/local:/opt/local
      - /opt/es_backup:/opt/es_backup
    ports:
      - 9300:9300
      - 9200:9200
    ulimits:
      nofile: 65536