version: "3"

services:
  content:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ALF_STORAGE_BUCKET=${ALF_STORAGE_BUCKET}
      - TG_REGION=${TG_REGION}
    volumes:
      - /opt/scripts:/opt/scripts
    entrypoint: [ "sh", "/opt/scripts/alfresco_database_backup.sh", "content-sync" ]
  psql:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ALF_DB_HOST=${ALF_DB_HOST}
      - ALF_DB_NAME=${ALF_DB_NAME}
      - ALF_DB_PASSWORD_SSM=${ALF_DB_PASSWORD_SSM}
      - ALF_DB_USERNAME_SSM=${ALF_DB_USERNAME_SSM}
      - TG_REGION=${TG_REGION}
    volumes:
      - /opt/scripts:/opt/scripts
      - /opt/eslocal/psql:/opt/local
    entrypoint: [ "sh", "/opt/scripts/alfresco_database_backup.sh", "db-backup" ]
  vacuum:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ALF_DB_HOST=${ALF_DB_HOST}
      - ALF_DB_NAME=${ALF_DB_NAME}
      - ALF_DB_PASSWORD_SSM=${ALF_DB_PASSWORD_SSM}
      - ALF_DB_USERNAME_SSM=${ALF_DB_USERNAME_SSM}
      - TG_REGION=${TG_REGION}
    volumes:
      - /opt/scripts:/opt/scripts
    entrypoint: [ "sh", "/opt/scripts/alfresco_database_maintenance.sh", "vacuum-tables" ]
  elasticsearch:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ELK_BACKUP_BUCKET=${ELK_BACKUP_BUCKET}
      - ELK_S3_REPO_NAME=${ELK_S3_REPO_NAME}
      - TG_REGION=${TG_REGION}
      - ES_HOST=${ES_MIGRATION_HOST}
      - ES_SNAPSHOT_NAME=alfresco_snapshot
      - CONFIG_BUCKET=${CONFIG_BUCKET}
      - DAYS_TO_DELETE=${DAYS_TO_DELETE}
    volumes:
      - /opt/scripts:/opt/scripts
    entrypoint: [ "sh", "/opt/scripts/alfresco_database_backup.sh", "elasticsearch-backup" ]
