version: "3"

services:
  elasticsearch-manager:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:0.0.219-alpha
    environment:
      - APP_ENVIRONMENT=dev
      - VERBOSE_MODE=True
      - ES_HOST=elasticsearch.${INTERNAL_DOMAIN}
      - CONFIG_BUCKET=${CONFIG_BUCKET}
      - ES_LB_DNS=${ES_LB_DNS}
    volumes:
      - /opt/scripts:/opt/scripts
      - /opt/local:/opt/local
    entrypoint: [ "sh", "/opt/scripts/es6-restore.sh" ]