
version: "3"

services:
  elasticsearch-manager:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:0.0.336-alpha
    environment:
      - APP_ENVIRONMENT=dev
      - VERBOSE_MODE=True
      - ES_HOST=${ES_MIGRATION_HOST}
      - ES_SNAPSHOT_NAME=${ES_SNAPSHOT_NAME}
      - CONFIG_BUCKET=${CONFIG_BUCKET}
      - ALF_RESTORE_STATUS=${ALF_RESTORE_STATUS}
      - ELK_BACKUP_BUCKET=${ELK_BACKUP_BUCKET}
      - ELK_S3_REPO_NAME=${ELK_S3_REPO_NAME}
      - CREATE_MIGRATION_REPO=True
      - ES_MIGRATION_SNAPSHOT_NAME=${ES_MIGRATION_SNAPSHOT_NAME}
    volumes:
      - /opt/scripts:/opt/scripts
      - /opt/local:/opt/local
    entrypoint: [ "sh", "/opt/scripts/es5-restore.sh" ]
    depends_on:
      - elasticsearch
  elasticsearch:
    image: mojdigitalstudio/hmpps-elasticsearch-5:latest
    volumes:
      - /opt/local:/opt/local
      - /opt/es_backup:/opt/es_backup
    environment:
      - ES_JVM_MEM=2g
    ports:
      - 9300:9300
      - 9200:9200
    ulimits:
      nofile: 65536
