
version: "3"

services:
  elasticsearch-manager:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - VERBOSE_MODE=True
      - ES_HOST=elasticsearch
      - ES_SNAPSHOT_NAME=${ES_SNAPSHOT_NAME}
      - CONFIG_BUCKET=${CONFIG_BUCKET}
      - ALF_RESTORE_STATUS=${ALF_RESTORE_STATUS}
    volumes:
      - /opt/scripts:/opt/scripts
      - /opt/local:/opt/local
    entrypoint: [ "sh", "/opt/scripts/es5-restore.sh" ]
    depends_on:
      - elasticsearch
  elasticsearch:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - ES_VERSION=5.6.16
    volumes:
      - /opt/local:/opt/local
      - /opt/es_backup:/opt/es_backup
    environment:
      - ES_JVM_MEM=5g
    ports:
      - 9300:9300
      - 9200:9200
    ulimits:
      nofile: 65536