version: "3"

services:
  vacuum:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ALF_DB_HOST=${ALF_DB_HOST}
      - ALF_DB_NAME=${ALF_DB_NAME}
      - ALF_DB_PASSWORD_SSM=${ALF_DB_PASSWORD_SSM}
      - ALF_DB_USERNAME_SSM=${ALF_DB_USERNAME_SSM}
      - TG_REGION=${TG_REGION}
    volumes:
      - /opt/scripts:/opt/scripts
    entrypoint: [ "sh", "/opt/scripts/alfresco_database_maintenance.sh", "vacuum-tables" ]
