version: "3"

services:
  elasticsearch:
    image: mojdigitalstudio/hmpps-elasticsearch:latest
    container_name: es
    environment:
      - HMPPS_ES_CLUSTER_NAME=es-clust
      - HMPPS_ES_NODE_NAME=es1
      - HMPPS_ES_DISCOVERY_TYPE=single-node
      - HMPPS_ES_NETWORK_PUBLISH_HOST=0.0.0.0
      - HMPPS_ES_PATH_REPO=/opt/es_backups
      - HMPPS_ES_BOOTSTRAP_MEMORY_LOCK=true
      - HMPPS_JVM_HEAPSIZE=2g
      - HMPPS_ES_DEPLOYMENT_TYPE=ec2
      - HMPPS_ES_DEPLOYMENT_TAG=es_cluster_discovery
      - HMPPS_ES_DEPLOYMENT_VALUE=test
    volumes:
      - ./elasticsearch.yml.tmpl:/etc/confd/templates/elasticsearch.yml.tmpl
    ports:
      - 9300:9300
      - 9200:9200
    ulimits:
      nofile: 65536
  es_client:
    build:
      context: ./services/es_client
      dockerfile: Dockerfile
    environment:
      - APP_ENVIRONMENT=test
    volumes:
      - ./services/es_client/reports:/tmp/reports
    depends_on:
      - elasticsearch