version: "3"

services:
  elasticsearch:
    image: mojdigitalstudio/hmpps-elasticsearch-manager:latest
    environment:
      - APP_ENVIRONMENT=dev
      - ALF_BACKUP_BUCKET=${ALF_BACKUP_BUCKET}
      - ELK_BACKUP_BUCKET=${ELK_BACKUP_BUCKET}
      - ELK_S3_REPO_NAME=${ELK_S3_REPO_NAME}
      - TG_REGION=${TG_REGION}
      - ES_HOST=${ES_MIGRATION_HOST}
      - ES_SNAPSHOT_NAME=alfresco_snapshot
      - CONFIG_BUCKET=${CONFIG_BUCKET}
      - DAYS_TO_DELETE=${DAYS_TO_DELETE}
    volumes:
      - /opt/scripts:/opt/scripts
    entrypoint: ["sh", "/opt/scripts/es_migration.sh", "elasticsearch-backup"]
