---
- name: Create
  hosts: localhost
  connection: local
  vars_files:
    - vars/snapshot-vars.yml
  tasks:
    - name: load json variables
      set_fact:
        db_info: "{{ lookup('file', '../ansible/data.json') | from_json }}"

    - name: set base facts
      set_fact:
        target_account: "{{ db_info['targets'][environment_name]['account_id'] }}"
        src_id: "{{ db_info['source']['id'] }}"
        target_id: "{{ db_info['targets'][environment_name]['id'] }}"

    - name: source database instance id
      debug:
        msg: "{{ src_id }}"

    - name: target database instance id
      debug:
        msg: "{{ target_id }}"

    - name: create snapshot and destroy target instance
      include: snapshot.yml
      when: create_snapshot | bool
