---
- name: Trigger lambda function
  hosts: localhost
  connection: local
  vars:
    iam_user_profile: "{{ lookup('env', 'IAM_USER_PROFILE')}}"
    environment_name: "{{ lookup('env', 'ENVIRONMENT_NAME')}}"
    aws_region: "eu-west-2"
    function_name: AlfSubmitS3TaskCopy
  tasks:
    - name: load json variables
      set_fact:
        db_info: "{{ lookup('file', '../database_snapshot/data.json') | from_json }}"

    - name: set base facts
      set_fact:
        target_account: "{{ db_info['targets'][environment_name]['account_id'] }}"

    - name: set iam role facts
      set_fact:
        target_iam_role: "{{ 'arn:aws:iam::' + target_account + ':role/terraform' }}"

    - name: get aws creds for target account
      sts_assume_role:
        role_arn: "{{ target_iam_role }}"
        role_session_name: target-ci-task
        profile: "{{ iam_user_profile }}"
      register: target_role

    - name: set ansible environment facts for target account
      set_fact:
        target_access_key_id: "{{ target_role.sts_creds.access_key }}"
        target_secret_access_key: "{{ target_role.sts_creds.secret_key }}"
        target_security_token: "{{ target_role.sts_creds.session_token }}"

    - name: trigger content-sync lambda function
      execute_lambda:
        name: "{{ function_name }}"
        wait: yes
        aws_access_key: "{{ target_access_key_id }}"
        aws_secret_key: "{{ target_secret_access_key }}"
        security_token: "{{ target_security_token }}"
      register: response

    - name: function output
      debug:
        msg: "{{ response }}"
